cursor #f9ddd3
cursor_text_color #dbc1b7

foreground            #f9ddd3
background            #1d100b
selection_foreground  #48290c
selection_background  #efbc94
url_color             #ffb598
color0   #1d100b
color1   #e14982
color2   #99d66e
color3   #dbab7b
color4   #bd6c4c
color5   #bf9281
color6   #ffb598
color7   #abb2bf
color8   #5c6370
color9   #e05f92
color10   #abe086
color11   #e8c097
color12   #ffc2a3
color13   #b76055
color14   #9b7052
color15   #ffffff
