[colors]
background = '#1d100b'
foreground = '#f9ddd3'

cursor_bg = '#ffb598'
cursor_fg = '#1d100b'
cursor_border = '#ffb598'

selection_bg = '#7e2c00'
selection_fg = '#f9ddd3'

ansi = ['#1d100b', '#e14982', '#99d66e', '#dbab7b', '#bd6c4c', '#bf9281', '#ffb598', '#abb2bf']
brights = ['#5c6370', '#e05f92', '#abe086', '#e8c097', '#ffc2a3', '#b76055', '#9b7052', '#ffffff']
